version: "3.9"
services:
  flask-api:
    container_name: flask_api
    image: flask_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - libdb
    environment:
      - DB_URL=postgresql://postgres:postgres@libdb:5432/librarydb

  libdb:
    container_name: libdb
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: librarydb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}